---
title: "A New Perspective on Global Animal Production"
author: "Adrian Hirt"
date: "`r Sys.Date()`"
output: 
  ioslides_presentation
    
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
library(dplyr)
library(ggplot2)

```

## The Purpose

To visualize how the ratio of **animals slaughtered to inhabitants** has shifted globally over the course of the last six decades. 

## Why?
Animal agriculture sits at the intersection of some of the most pressing issues of our time. Intensive animal farming is a major factor in antimicrobial resistance, climate change and animal welfare. Particularly in developed countries the magnitude of the industry is often overlooked - this projects aims to visualize a broken system. 

## How?

The visualization will consist of two interactive world maps, presented as a shiny web application.  

1. The user will be able to select species and year. The map will be color-coded, indicating the country with the relative highest ratio in the given year. 
2. The user will be able to select a species and be presented with a color-coded world map, highlighting the countries with the most significant increase of slaughter numbers per capita.


## The Data

### Production/Slaughter Data

- From [FAOSTAT](https://www.fao.org/faostat/en/#home), run by the Food and Agriculture Organization of the United Nations ([FAO](https://www.fao.org/home/en)).
- Data mostly available for developed countries
- For most developing countries incomplete data (i.e., only some species or incomplete timeframe)

## The Data

### Population Data

- From the [Department of Economic and Social Affairs of the United Nations](https://population.un.org/wpp/Download/Standard/Population/)

## Shiny App

- Interactive [Choropleth Map](https://leafletjs.com/examples/choropleth/)
- Built on [leaflet](https://rstudio.github.io/leaflet/) library
- Information displayed on hover
